services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: empty-fastapy-hexagonal
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    restart: on-failure
    env_file:
      - ./env_vars/backend.env
      - ./env_vars/database.env
    volumes:
      - ./:/app

  db:
    container_name: dev-recaudos-database
    image: postgres:16.2
    env_file:
      - ./env_vars/database.env
    ports:
      - "5432:5432"
    volumes:
      - dev_recaudos_data:/var/lib/postgresql/data


  adminer:
    container_name: dev-empty-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  dev_recaudos_data: